name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Pas 500k
      id: pas-500k
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Pas 500k
        setup-command: javac Nomor1.java
        command: java Nomor1
        input: '500000'
        expected-output: '50000.0'
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Under 500k
      id: under-500k
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Under 500k
        setup-command: javac Nomor1.java
        command: java Nomor1
        input: '40000'
        expected-output: '40000.0'
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Di atas 500k
      id: di-atas-500k
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Di atas 500k
        setup-command: javac Nomor1.java
        command: java Nomor1
        input: '1000000'
        expected-output: '125000.0'
        comparison-method: exact
        timeout: 10
        max-score: 20
    - name: Tanpa komisi
      id: tanpa-komisi
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Tanpa komisi
        setup-command: javac Nomor1.java
        command: java Nomor1
        input: '0'
        expected-output: '0.0'
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Test 1
      id: test-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 1
        setup-command: javac Nomor2.java
        command: java Nomor2
        input: |-
          3
          4
          Y
          2
          1
          Y
          1
          3
          N
        expected-output: |-
          3
          375000.0
        comparison-method: contains
        timeout: 10
        max-score: 50
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PAS-500K_RESULTS: "${{steps.pas-500k.outputs.result}}"
        UNDER-500K_RESULTS: "${{steps.under-500k.outputs.result}}"
        DI-ATAS-500K_RESULTS: "${{steps.di-atas-500k.outputs.result}}"
        TANPA-KOMISI_RESULTS: "${{steps.tanpa-komisi.outputs.result}}"
        TEST-1_RESULTS: "${{steps.test-1.outputs.result}}"
      with:
        runners: pas-500k,under-500k,di-atas-500k,tanpa-komisi,test-1
